export type Difficulty = 'easy' | 'medium' | 'hard';

export interface Word {
  word: string;
  category: string;
  difficulty: Difficulty;
}

export const WORD_BANK: Word[] = [
  // an animal
  { word: 'cat', category: 'an animal', difficulty: 'easy' },
  { word: 'dog', category: 'an animal', difficulty: 'easy' },
  { word: 'horse', category: 'an animal', difficulty: 'easy' },
  { word: 'elephant', category: 'an animal', difficulty: 'easy' },
  { word: 'giraffe', category: 'an animal', difficulty: 'easy' },
  { word: 'penguin', category: 'an animal', difficulty: 'easy' },
  { word: 'kangaroo', category: 'an animal', difficulty: 'medium' },
  { word: 'dolphin', category: 'an animal', difficulty: 'medium' },
  { word: 'tiger', category: 'an animal', difficulty: 'easy' },
  { word: 'rabbit', category: 'an animal', difficulty: 'easy' },
  { word: 'hedgehog', category: 'an animal', difficulty: 'medium' },
  { word: 'octopus', category: 'an animal', difficulty: 'medium' },
  { word: 'camel', category: 'an animal', difficulty: 'medium' },

  // a vehicle
  { word: 'bicycle', category: 'a vehicle', difficulty: 'easy' },
  { word: 'motorbike', category: 'a vehicle', difficulty: 'easy' },
  { word: 'tractor', category: 'a vehicle', difficulty: 'easy' },
  { word: 'helicopter', category: 'a vehicle', difficulty: 'easy' },
  { word: 'submarine', category: 'a vehicle', difficulty: 'medium' },
  { word: 'caravan', category: 'a vehicle', difficulty: 'medium' },
  { word: 'lorry', category: 'a vehicle', difficulty: 'easy' },
  { word: 'ambulance', category: 'a vehicle', difficulty: 'easy' },
  { word: 'aeroplane', category: 'a vehicle', difficulty: 'easy' },
  { word: 'hovercraft', category: 'a vehicle', difficulty: 'hard' },
  { word: 'tram', category: 'a vehicle', difficulty: 'medium' },
  { word: 'bulldozer', category: 'a vehicle', difficulty: 'medium' },
  { word: 'rickshaw', category: 'a vehicle', difficulty: 'hard' },

  // a building
  { word: 'lighthouse', category: 'a building', difficulty: 'easy' },
  { word: 'castle', category: 'a building', difficulty: 'easy' },
  { word: 'cathedral', category: 'a building', difficulty: 'medium' },
  { word: 'windmill', category: 'a building', difficulty: 'medium' },
  { word: 'skyscraper', category: 'a building', difficulty: 'easy' },
  { word: 'cottage', category: 'a building', difficulty: 'easy' },
  { word: 'barn', category: 'a building', difficulty: 'easy' },
  { word: 'greenhouse', category: 'a building', difficulty: 'medium' },
  { word: 'warehouse', category: 'a building', difficulty: 'medium' },
  { word: 'mosque', category: 'a building', difficulty: 'medium' },
  { word: 'palace', category: 'a building', difficulty: 'medium' },
  { word: 'bungalow', category: 'a building', difficulty: 'hard' },
  { word: 'observatory', category: 'a building', difficulty: 'hard' },

  // a fruit
  { word: 'apple', category: 'a fruit', difficulty: 'easy' },
  { word: 'banana', category: 'a fruit', difficulty: 'easy' },
  { word: 'pineapple', category: 'a fruit', difficulty: 'easy' },
  { word: 'mango', category: 'a fruit', difficulty: 'easy' },
  { word: 'strawberry', category: 'a fruit', difficulty: 'easy' },
  { word: 'watermelon', category: 'a fruit', difficulty: 'easy' },
  { word: 'kiwi', category: 'a fruit', difficulty: 'medium' },
  { word: 'pomegranate', category: 'a fruit', difficulty: 'medium' },
  { word: 'papaya', category: 'a fruit', difficulty: 'medium' },
  { word: 'apricot', category: 'a fruit', difficulty: 'medium' },
  { word: 'fig', category: 'a fruit', difficulty: 'hard' },
  { word: 'lychee', category: 'a fruit', difficulty: 'hard' },
  { word: 'plum', category: 'a fruit', difficulty: 'medium' },

  // a vegetable
  { word: 'carrot', category: 'a vegetable', difficulty: 'easy' },
  { word: 'potato', category: 'a vegetable', difficulty: 'easy' },
  { word: 'broccoli', category: 'a vegetable', difficulty: 'easy' },
  { word: 'cauliflower', category: 'a vegetable', difficulty: 'easy' },
  { word: 'aubergine', category: 'a vegetable', difficulty: 'medium' },
  { word: 'courgette', category: 'a vegetable', difficulty: 'medium' },
  { word: 'spinach', category: 'a vegetable', difficulty: 'medium' },
  { word: 'cabbage', category: 'a vegetable', difficulty: 'easy' },
  { word: 'pumpkin', category: 'a vegetable', difficulty: 'easy' },
  { word: 'beetroot', category: 'a vegetable', difficulty: 'medium' },
  { word: 'artichoke', category: 'a vegetable', difficulty: 'hard' },
  { word: 'radish', category: 'a vegetable', difficulty: 'medium' },
  { word: 'parsnip', category: 'a vegetable', difficulty: 'hard' },

  // a piece of furniture
  { word: 'wardrobe', category: 'a piece of furniture', difficulty: 'easy' },
  { word: 'bookcase', category: 'a piece of furniture', difficulty: 'easy' },
  { word: 'armchair', category: 'a piece of furniture', difficulty: 'easy' },
  { word: 'footstool', category: 'a piece of furniture', difficulty: 'medium' },
  { word: 'ottoman', category: 'a piece of furniture', difficulty: 'medium' },
  { word: 'chaise longue', category: 'a piece of furniture', difficulty: 'hard' },
  { word: 'cot', category: 'a piece of furniture', difficulty: 'medium' },
  { word: 'hammock', category: 'a piece of furniture', difficulty: 'medium' },
  { word: 'deckchair', category: 'a piece of furniture', difficulty: 'medium' },
  { word: 'bureau', category: 'a piece of furniture', difficulty: 'hard' },
  { word: 'bedstead', category: 'a piece of furniture', difficulty: 'hard' },
  { word: 'cabinet', category: 'a piece of furniture', difficulty: 'medium' },
  { word: 'bench', category: 'a piece of furniture', difficulty: 'easy' },

  // a musical instrument
  { word: 'guitar', category: 'a musical instrument', difficulty: 'easy' },
  { word: 'violin', category: 'a musical instrument', difficulty: 'easy' },
  { word: 'trumpet', category: 'a musical instrument', difficulty: 'easy' },
  { word: 'saxophone', category: 'a musical instrument', difficulty: 'easy' },
  { word: 'clarinet', category: 'a musical instrument', difficulty: 'medium' },
  { word: 'trombone', category: 'a musical instrument', difficulty: 'medium' },
  { word: 'xylophone', category: 'a musical instrument', difficulty: 'medium' },
  { word: 'accordion', category: 'a musical instrument', difficulty: 'medium' },
  { word: 'bagpipes', category: 'a musical instrument', difficulty: 'medium' },
  { word: 'harmonica', category: 'a musical instrument', difficulty: 'medium' },
  { word: 'ukulele', category: 'a musical instrument', difficulty: 'medium' },
  { word: 'cello', category: 'a musical instrument', difficulty: 'medium' },
  { word: 'tambourine', category: 'a musical instrument', difficulty: 'medium' },

  // a sport
  { word: 'football', category: 'a sport', difficulty: 'easy' },
  { word: 'tennis', category: 'a sport', difficulty: 'easy' },
  { word: 'badminton', category: 'a sport', difficulty: 'easy' },
  { word: 'cricket', category: 'a sport', difficulty: 'easy' },
  { word: 'rugby', category: 'a sport', difficulty: 'easy' },
  { word: 'boxing', category: 'a sport', difficulty: 'easy' },
  { word: 'swimming', category: 'a sport', difficulty: 'easy' },
  { word: 'wrestling', category: 'a sport', difficulty: 'medium' },
  { word: 'snooker', category: 'a sport', difficulty: 'medium' },
  { word: 'golf', category: 'a sport', difficulty: 'easy' },
  { word: 'fencing', category: 'a sport', difficulty: 'medium' },
  { word: 'archery', category: 'a sport', difficulty: 'medium' },
  { word: 'skiing', category: 'a sport', difficulty: 'easy' },

  // a job
  { word: 'teacher', category: 'a job', difficulty: 'easy' },
  { word: 'plumber', category: 'a job', difficulty: 'easy' },
  { word: 'electrician', category: 'a job', difficulty: 'easy' },
  { word: 'dentist', category: 'a job', difficulty: 'easy' },
  { word: 'florist', category: 'a job', difficulty: 'medium' },
  { word: 'librarian', category: 'a job', difficulty: 'medium' },
  { word: 'mechanic', category: 'a job', difficulty: 'easy' },
  { word: 'farmer', category: 'a job', difficulty: 'easy' },
  { word: 'journalist', category: 'a job', difficulty: 'medium' },
  { word: 'surgeon', category: 'a job', difficulty: 'medium' },
  { word: 'architect', category: 'a job', difficulty: 'medium' },
  { word: 'carpenter', category: 'a job', difficulty: 'medium' },
  { word: 'optician', category: 'a job', difficulty: 'hard' },

  // a body part
  { word: 'elbow', category: 'a body part', difficulty: 'easy' },
  { word: 'shoulder', category: 'a body part', difficulty: 'easy' },
  { word: 'kneecap', category: 'a body part', difficulty: 'medium' },
  { word: 'eyebrow', category: 'a body part', difficulty: 'easy' },
  { word: 'forehead', category: 'a body part', difficulty: 'easy' },
  { word: 'wrist', category: 'a body part', difficulty: 'easy' },
  { word: 'ankle', category: 'a body part', difficulty: 'easy' },
  { word: 'thumb', category: 'a body part', difficulty: 'easy' },
  { word: 'nostril', category: 'a body part', difficulty: 'medium' },
  { word: 'collarbone', category: 'a body part', difficulty: 'medium' },
  { word: 'eyelash', category: 'a body part', difficulty: 'medium' },
  { word: 'forearm', category: 'a body part', difficulty: 'medium' },
  { word: 'jaw', category: 'a body part', difficulty: 'medium' },

  // a weather phenomenon
  { word: 'thunderstorm', category: 'a weather phenomenon', difficulty: 'easy' },
  { word: 'rainbow', category: 'a weather phenomenon', difficulty: 'easy' },
  { word: 'hurricane', category: 'a weather phenomenon', difficulty: 'easy' },
  { word: 'blizzard', category: 'a weather phenomenon', difficulty: 'medium' },
  { word: 'drought', category: 'a weather phenomenon', difficulty: 'medium' },
  { word: 'tornado', category: 'a weather phenomenon', difficulty: 'easy' },
  { word: 'hailstorm', category: 'a weather phenomenon', difficulty: 'medium' },
  { word: 'fog', category: 'a weather phenomenon', difficulty: 'easy' },
  { word: 'frost', category: 'a weather phenomenon', difficulty: 'easy' },
  { word: 'monsoon', category: 'a weather phenomenon', difficulty: 'medium' },
  { word: 'heatwave', category: 'a weather phenomenon', difficulty: 'medium' },
  { word: 'sleet', category: 'a weather phenomenon', difficulty: 'hard' },
  { word: 'drizzle', category: 'a weather phenomenon', difficulty: 'medium' },

  // a kitchen item
  { word: 'kettle', category: 'a kitchen item', difficulty: 'easy' },
  { word: 'saucepan', category: 'a kitchen item', difficulty: 'easy' },
  { word: 'colander', category: 'a kitchen item', difficulty: 'medium' },
  { word: 'whisk', category: 'a kitchen item', difficulty: 'easy' },
  { word: 'spatula', category: 'a kitchen item', difficulty: 'medium' },
  { word: 'toaster', category: 'a kitchen item', difficulty: 'easy' },
  { word: 'blender', category: 'a kitchen item', difficulty: 'easy' },
  { word: 'chopping board', category: 'a kitchen item', difficulty: 'medium' },
  { word: 'rolling pin', category: 'a kitchen item', difficulty: 'medium' },
  { word: 'grater', category: 'a kitchen item', difficulty: 'medium' },
  { word: 'ladle', category: 'a kitchen item', difficulty: 'medium' },
  { word: 'sieve', category: 'a kitchen item', difficulty: 'medium' },
  { word: 'teapot', category: 'a kitchen item', difficulty: 'easy' },

  // a piece of clothing
  { word: 'cardigan', category: 'a piece of clothing', difficulty: 'easy' },
  { word: 'waistcoat', category: 'a piece of clothing', difficulty: 'medium' },
  { word: 'blazer', category: 'a piece of clothing', difficulty: 'medium' },
  { word: 'poncho', category: 'a piece of clothing', difficulty: 'medium' },
  { word: 'kimono', category: 'a piece of clothing', difficulty: 'medium' },
  { word: 'apron', category: 'a piece of clothing', difficulty: 'easy' },
  { word: 'scarf', category: 'a piece of clothing', difficulty: 'easy' },
  { word: 'beanie', category: 'a piece of clothing', difficulty: 'medium' },
  { word: 'mitten', category: 'a piece of clothing', difficulty: 'medium' },
  { word: 'tunic', category: 'a piece of clothing', difficulty: 'hard' },
  { word: 'dressing gown', category: 'a piece of clothing', difficulty: 'medium' },
  { word: 'cape', category: 'a piece of clothing', difficulty: 'medium' },
  { word: 'sombrero', category: 'a piece of clothing', difficulty: 'hard' },

  // a tool
  { word: 'hammer', category: 'a tool', difficulty: 'easy' },
  { word: 'screwdriver', category: 'a tool', difficulty: 'easy' },
  { word: 'spanner', category: 'a tool', difficulty: 'easy' },
  { word: 'chisel', category: 'a tool', difficulty: 'medium' },
  { word: 'scissors', category: 'a tool', difficulty: 'easy' },
  { word: 'pliers', category: 'a tool', difficulty: 'medium' },
  { word: 'drill', category: 'a tool', difficulty: 'easy' },
  { word: 'saw', category: 'a tool', difficulty: 'easy' },
  { word: 'file', category: 'a tool', difficulty: 'medium' },
  { word: 'mallet', category: 'a tool', difficulty: 'medium' },
  { word: 'crowbar', category: 'a tool', difficulty: 'medium' },
  { word: 'staple gun', category: 'a tool', difficulty: 'medium' },
  { word: 'spirit level', category: 'a tool', difficulty: 'hard' },

  // an event
  { word: 'wedding', category: 'an event', difficulty: 'easy' },
  { word: 'funeral', category: 'an event', difficulty: 'easy' },
  { word: 'festival', category: 'an event', difficulty: 'easy' },
  { word: 'pageant', category: 'an event', difficulty: 'hard' },
  { word: 'the Olympics', category: 'an event', difficulty: 'easy' },
  { word: 'tournament', category: 'an event', difficulty: 'medium' },
  { word: 'ceremony', category: 'an event', difficulty: 'medium' },
  { word: 'exhibition', category: 'an event', difficulty: 'medium' },
  { word: 'parade', category: 'an event', difficulty: 'medium' },
  { word: 'auction', category: 'an event', difficulty: 'medium' },
  { word: 'marathon', category: 'an event', difficulty: 'medium' },
  { word: 'election', category: 'an event', difficulty: 'medium' },
  { word: 'referendum', category: 'an event', difficulty: 'hard' },

  // a drink
  { word: 'lemonade', category: 'a drink', difficulty: 'easy' },
  { word: 'cocoa', category: 'a drink', difficulty: 'easy' },
  { word: 'espresso', category: 'a drink', difficulty: 'easy' },
  { word: 'cappuccino', category: 'a drink', difficulty: 'easy' },
  { word: 'smoothie', category: 'a drink', difficulty: 'easy' },
  { word: 'milkshake', category: 'a drink', difficulty: 'easy' },
  { word: 'cordial', category: 'a drink', difficulty: 'medium' },
  { word: 'cider', category: 'a drink', difficulty: 'medium' },
  { word: 'sherry', category: 'a drink', difficulty: 'medium' },
  { word: 'prosecco', category: 'a drink', difficulty: 'medium' },
  { word: 'kombucha', category: 'a drink', difficulty: 'hard' },
  { word: 'tonic water', category: 'a drink', difficulty: 'medium' },
  { word: 'mocktail', category: 'a drink', difficulty: 'medium' },
];